# Generated by Django 2.1.3 on 2018-12-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token_name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telegram_id', models.CharField(max_length=200)),
                ('exchanges', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('press_release_national', models.BooleanField()),
                ('press_release_crypto', models.BooleanField()),
                ('press_release_premium', models.BooleanField()),
                ('bounty', models.BooleanField()),
                ('seo', models.BooleanField()),
                ('reviews_listing', models.BooleanField()),
                ('reviews_ico', models.BooleanField()),
                ('facebook', models.BooleanField()),
                ('reddit', models.BooleanField()),
                ('twitter', models.BooleanField()),
                ('youtube', models.BooleanField()),
            ],
        ),
    ]
