# Generated by Django 2.1.3 on 2018-12-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.CharField(max_length=16384),
        ),
        migrations.AlterField(
            model_name='proposalrequest',
            name='description',
            field=models.CharField(blank=True, max_length=16384),
        ),
    ]
